### ISSUE TITLE
SQL Support?

### ISSUE THREAD

**Issue by fmohican** [Chocorean/authmod#1]
Hi
Does your mod support SQL server ? (remote storage)

**Comment by fmohican** [comment]
i mean the plugins should store "user password" in database, not in file.

**Comment by fmohican** [comment]
and also you should encrypt user password instead to hash.

I mean to use "salt" [password(hash) + salt] another hash = stored password 

or to use bcrypt algorithm

**Comment by Chocorean** [comment]
I see! It doesn't support it yet as I want it to stay simple, but this is a great idea.

I know about salting, I've already planned it, but I'm working on a lot of different things at the same time and I haven't done it yet :)

**Comment by fmohican** [comment]
yah xD that nice, well , i'm waiting for sql support, even if they are just hashed.

**Comment by Mcdostone** [comment]
I have worked on it #2 !

**Comment by Chocorean** [comment]
Finally done ! -> [clickme](https://github.com/Chocorean/authmod/releases/tag/2.0) <-
