### ISSUE TITLE
Hostile mobs ignore player

### ISSUE THREAD

**Issue by gollariel** [Chocorean/authmod#12]
After installing the latest version on the server, the enemy starts ignoring me... The previous version works well

**Comment by Chocorean** [comment]
Do you mean that, after logging in, hostile still do not detect players ?

**Comment by Chocorean** [comment]
Fixed in commit [7a7755cba](https://github.com/Chocorean/authmod/commit/7a7755cba61058c7a4232638a02e599c3855214c)
