### ISSUE TITLE
Enhancment. Email for each login

### ISSUE THREAD

**Issue by gollariel** [Chocorean/authmod#15]
Would be nice to not required email for each login. When we make the account, we have a name. I know, now we potentially can have multiple players for each account, but I think its a bit tricky for users to type email each time on login

**Comment by Chocorean** [comment]
Yes we know about that. An option will be available soon giving you the choice of using email or not

**Comment by Mcdostone** [comment]
I need time to test the feature, it should be available soon!

**Comment by gollariel** [comment]
Thanks a lot! Will wait for new release :+1:
