### ISSUE TITLE
I can't use file strategy - it dont work

### ISSUE THREAD

**Issue by egori477** [Chocorean/authmod#16]
V 1.12.2 , platform - forge. Last version of this mod.
csv file was create by mod, and I registered in it, but when I enter on server (or another player) - login command dont work. I press: /login (mail) (pass) ; /login (pass) and enother wariants... nothing! Only repeat registration command ... 

Please, correct it or you can say me how I can do file strategy only with nickname and pass? Mb reccomend another mod... I dont know... I need Autorisation mod on server!

**Comment by Mcdostone** [comment]
We will fix this issue soon, be patient 👍

**Comment by egori477** [comment]
And, can you help to understand:
How do it on server or nonluniz plaform?

> Getting started for administrators
stop your minecraft server.
Add the latest version of the authmod jar in the mods directory:
# execute this in the mods folder
curl -s https://api.github.com/repos/chocorean/authmod/releases/latest \
  | grep "browser_download_url.*jar" \
  | cut -d : -f 2,3 \
  | tr -d \" \
  | wget -qi -
Now, we configure the authmod. Go under the config folder and download the cfg template file:

**Comment by Chocorean** [comment]
Maj + Right click and select open Powershell; you might be able to execute those commands

**Comment by Mcdostone** [comment]
2.6 is available
