### ISSUE TITLE
add mod after serveur work

### ISSUE THREAD

**Issue by croziors** [Chocorean/authmod#26]
**Describe the bug**
hello
i have serveur with player i add mod after and all player lost all data i think mod does not use players.dat which already exists

**Comment by Chocorean** [comment]
Can you please add your minecraft version, the authmod version you are using, be more specific about your issue and finally add your server logs ?

**Comment by croziors** [comment]
authmod-3.2.jar
minecraft 1.12.2
but i know the probleme because i disabled online check in serveur
so first in need all people register with online mod true  after i can disabled online check ?

**Comment by Chocorean** [comment]
The `online-mode` server parameter has not impact on Authmod ; they don't interact.

I still don't understand what your problem is. All players have to do is type `/register <password> <confirm_password> when they log in for the first time and use `/login <password>` for next times. Make sure you correctly edited the mod config file

**Comment by croziors** [comment]
but when i disabled online mod i don t have same player data config

**Comment by Chocorean** [comment]
Authmod has nothing to do with this...

**Comment by croziors** [comment]
i send u log could you delete after url

**Comment by croziors** [comment]
http://195.154.184.26/log/

**Comment by Chocorean** [comment]
There is nothing regarding authmod in the log file you sent ; A quick view to your `mods/` folder showed me authmod is not inside it... Put it again, run your server, and when you experience what you think is a bug, just stop your server, reopen an issue and include the log file please.
