### ISSUE TITLE
Add a way for ops to register players when /register is disabled

### ISSUE THREAD

**Issue by Chocorean** [Chocorean/authmod#28]
- a script ?
- /register is only disabled for basic players (see permission level)

**Comment by Mcdostone** [comment]
Ops can manually add players either in the `authmod.csv` file  or the database:

Resources:
 - [bcrypt calculator](https://www.dailycred.com/article/bcrypt-calculator): generate a hash using the bcrypt algorithm.

**Comment by Chocorean** [comment]
Fix by d251eac
