### ISSUE TITLE
Add salt in config

### ISSUE THREAD

**Issue by Chocorean** [Chocorean/authmod#29]

**Comment by Chocorean** [comment]
Un peu de taff pour toi bb

**Comment by Mcdostone** [comment]
Continuez Jackson, vous m'intéressez. De quoi s'agit-il?

**Comment by Chocorean** [comment]
Est ce que ca a un intérêt de permettre aux admins de choisir leur sel? J'pense aux gens qui désactive /register, et qui veulent remplir leur bdd a la mano ?

**Comment by Chocorean** [comment]
worthless
