### ISSUE TITLE
I can't get on the server

### ISSUE THREAD

**Issue by JeanShamayin** [Chocorean/authmod#32]
**I can't get on the server**

I installed the MOD and now I can't login to the server to register and login.

**Versions**

Minecraft 1.15.2 Forge 31.9.2 + AuthMod 4.0

**Log files**

←[m←[32m[14:34:38] [Server thread/INFO] [minecraft/ServerLoginNetHandler]: com.mojang.authlib.GameProfile@f3f0021[id=<null>,name=JeanShamayin,properties={},legacy=false] (/127.0.0.1:55803) lost connection: Disconnected
←[m←[32m[14:34:42] [Server thread/INFO] [minecraft/ServerLoginNetHandler]: com.mojang.authlib.GameProfile@6e6b2ec1[id=<null>,name=JeanShamayin,properties={},legacy=false] (/127.0.0.1:55806) lost connection: Disconnected
←[m←[32m[14:34:43] [Server thread/INFO] [minecraft/ServerLoginNetHandler]: com.mojang.authlib.GameProfile@59246d68[id=<null>,name=JeanShamayin,properties={},legacy=false] (/127.0.0.1:55809) lost connection: Disconnected

**Additional context**

https://prnt.sc/t093ya

https://prnt.sc/t0947v

**Comment by Chocorean** [comment]
Please use 4.2 version
I woukd also recommend using forge 1.15.2-31.1.36

Tell me if the problem still happens

**Comment by JeanShamayin** [comment]
Okay, I'll test it and let you know if it's resolved!

**Comment by JeanShamayin** [comment]
Still with the same error!

**Comment by Chocorean** [comment]
is authmod the only mod you are using? Can you attach the full server log please?

**Comment by JeanShamayin** [comment]
**No, I use a MODPACK made by me!**

---> https://prnt.sc/t0b5qp <--- MODS

**Log Full**

`C:\Users\JeanShamayin\Desktop\MINE RPG\RPG NOVO>java -Xmx5024M -Xms1024M -jar forge-1.15.2-31.2.9.jar nogui
2020-06-15 16:28:08,542 main WARN Advanced terminal features are not available in this environment
←[32m[16:28:08] [main/INFO] [cp.mo.mo.Launcher/MODLAUNCHER]: ModLauncher running: args [--gameDir, ., --launchTarget, fmlserver, --fml.forgeVersion, 31.2.9, --fml.mcpVersion, 20200515.085601, --fml.mcVersion, 1.15.2, --fml.forgeGroup, net.minecraftforge, nogui]
←[m←[32m[16:28:08] [main/INFO] [cp.mo.mo.Launcher/MODLAUNCHER]: ModLauncher 5.1.0+69+master.79f13f7 starting: java version 1.8.0_251 by Oracle Corporation
←[m←[32m[16:28:09] [main/INFO] [ne.mi.fm.lo.FixSSL/CORE]: Added Lets Encrypt root certificates as additional trust
←[m←[32m[16:28:10] [main/INFO] [cp.mo.mo.LaunchServiceHandler/MODLAUNCHER]: Launching target 'fmlserver' with arguments [--gameDir, ., nogui]
←[m←[33m[16:28:20] [main/WARN] [minecraft/Commands]: Ambiguity between arguments [teleport, destination] and [teleport, targets] with inputs: [Player, 0123, @e, dd12be42-52a9-4a91-a8a1-11c01849e498]
←[m←[33m[16:28:20] [main/WARN] [minecraft/Commands]: Ambiguity between arguments [teleport, location] and [teleport, destination] with inputs: [0.1 -0.5 .9, 0 0 0]
←[m←[33m[16:28:20] [main/WARN] [minecraft/Commands]: Ambiguity between arguments [teleport, location] and [teleport, targets] with inputs: [0.1 -0.5 .9, 0 0 0]
←[m←[33m[16:28:20] [main/WARN] [minecraft/Commands]: Ambiguity between arguments [teleport, targets] and [teleport, destination] with inputs: [Player, 0123, dd12be42-52a9-4a91-a8a1-11c01849e498]
←[m←[33m[16:28:20] [main/WARN] [minecraft/Commands]: Ambiguity between arguments [teleport, targets, location] and [teleport, targets, destination] with inputs: [0.1 -0.5 .9, 0 0 0]
←[m←[32m[16:28:20] [Server thread/INFO] [minecraft/DedicatedServer]: Starting minecraft server version 1.15.2
←[m←[32m[16:28:22] [modloading-worker-3/INFO] [mo.az.az.AzureRPGItemsMod/]: Loading config: C:\Users\JeanShamayin\Desktop\MINE RPG\RPG NOVO\config\azurerpgitems-config.toml
←[m←[32m[16:28:22] [modloading-worker-3/INFO] [mo.az.az.AzureRPGItemsMod/]: Built config: C:\Users\JeanShamayin\Desktop\MINE RPG\RPG NOVO\config\azurerpgitems-config.toml
←[m←[32m[16:28:22] [modloading-worker-0/INFO] [AuthMod/]: %s %s
←[m←[32m[16:28:22] [modloading-worker-3/INFO] [mo.az.az.AzureRPGItemsMod/]: Loaded config: C:\Users\JeanShamayin\Desktop\MINE RPG\RPG NOVO\config\azurerpgitems-config.toml
←[m←[32m[16:28:23] [modloading-worker-3/INFO] [STDOUT/]: [com.robertx22.mine_and_slash.mmorpg.MMORPG:<init>:105]: Starting Mine and Slash
←[m←[32m[16:28:23] [modloading-worker-2/INFO] [ne.mi.co.ForgeMod/FORGEMOD]: Forge mod loading, version 31.2.9, for MC 1.15.2 with MCP 20200515.085601
←[m←[32m[16:28:23] [modloading-worker-2/INFO] [ne.mi.co.MinecraftForge/FORGE]: MinecraftForge v31.2.9 Initialized
←[m←[32m[16:28:24] [modloading-worker-1/INFO] [JarSignVerifier/]: Mod uteamcore is signed with a valid certificate.
←[m←[32m[16:28:24] [modloading-worker-0/INFO] [behgameon/]: Loading config: C:\Users\JeanShamayin\Desktop\MINE RPG\RPG NOVO\config\behgameon-config.toml
←[m←[32m[16:28:24] [modloading-worker-0/INFO] [behgameon/]: Built config: C:\Users\JeanShamayin\Desktop\MINE RPG\RPG NOVO\config\behgameon-config.toml
←[m←[32m[16:28:24] [modloading-worker-0/INFO] [behgameon/]: Loaded config: C:\Users\JeanShamayin\Desktop\MINE RPG\RPG NOVO\config\behgameon-config.toml
←[m←[33m[16:28:25] [modloading-worker-0/WARN] [ne.mi.se.pe.PermissionAPI/]: Replacing net.minecraftforge.server.permission.DefaultPermissionHandler with com.feed_the_beast.mods.ftbranks.impl.PermissionAPIWrapper
←[m←[32m[16:28:25] [modloading-worker-0/INFO] [JarSignVerifier/]: Mod usefulbackpacks is signed with a valid certificate.
←[m←[32m[16:28:32] [modloading-worker-3/INFO] [STDOUT/]: [com.robertx22.mine_and_slash.database.talent_tree.csv_parser.TalentParser:parse:27]: Registered all 349 perks to the talent tree!
←[m←[32m[16:28:32] [modloading-worker-3/INFO] [STDOUT/]: [com.robertx22.mine_and_slash.blocks.scrabble.ScrabbleTile:loadWordList:402]: Loaded 279496 words to the dictionary.
←[m←[33m[16:28:32] [modloading-worker-3/WARN] [minecraft/EntityType]: No data fixer registered for entity mmorpg:holy_spear
←[m←[33m[16:28:32] [modloading-worker-3/WARN] [minecraft/EntityType]: No data fixer registered for entity mmorpg:blizzard
←[m←[33m[16:28:32] [modloading-worker-3/WARN] [minecraft/EntityType]: No data fixer registered for entity mmorpg:frostball
←[m←[33m[16:28:32] [modloading-worker-3/WARN] [minecraft/EntityType]: No data fixer registered for entity mmorpg:whirlpool
←[m←[33m[16:28:32] [modloading-worker-3/WARN] [minecraft/EntityType]: No data fixer registered for entity mmorpg:tidal_wave
←[m←[33m[16:28:32] [modloading-worker-3/WARN] [minecraft/EntityType]: No data fixer registered for entity mmorpg:poison_ball
←[m←[33m[16:28:32] [modloading-worker-3/WARN] [minecraft/EntityType]: No data fixer registered for entity mmorpg:thunderstorm
←[m←[33m[16:28:32] [modloading-worker-3/WARN] [minecraft/EntityType]: No data fixer registered for entity mmorpg:thunder_spear
←[m←[33m[16:28:32] [modloading-worker-3/WARN] [minecraft/EntityType]: No data fixer registered for entity mmorpg:lightning_totem
←[m←[33m[16:28:32] [modloading-worker-3/WARN] [minecraft/EntityType]: No data fixer registered for entity mmorpg:fireball
←[m←[33m[16:28:32] [modloading-worker-3/WARN] [minecraft/EntityType]: No data fixer registered for entity mmorpg:fire_bomb
←[m←[33m[16:28:32] [modloading-worker-3/WARN] [minecraft/EntityType]: No data fixer registered for entity mmorpg:seeker_flame
←[m←[33m[16:28:32] [modloading-worker-3/WARN] [minecraft/EntityType]: No data fixer registered for entity mmorpg:volcano
←[m←[33m[16:28:32] [modloading-worker-3/WARN] [minecraft/EntityType]: No data fixer registered for entity mmorpg:ranger_arrow
←[m←[33m[16:28:32] [modloading-worker-3/WARN] [minecraft/EntityType]: No data fixer registered for entity mmorpg:arrow_storm
←[m←[33m[16:28:32] [modloading-worker-3/WARN] [minecraft/EntityType]: No data fixer registered for entity mmorpg:divine_tribulation
←[m←[33m[16:28:32] [modloading-worker-3/WARN] [minecraft/EntityType]: No data fixer registered for entity mmorpg:seed_entity
←[m←[33m[16:28:32] [modloading-worker-3/WARN] [minecraft/EntityType]: No data fixer registered for entity mmorpg:trader
←[m←[33m[16:28:32] [modloading-worker-3/WARN] [minecraft/EntityType]: No data fixer registered for entity mmorpg:leaping_zombie
←[m←[33m[16:28:32] [modloading-worker-3/WARN] [minecraft/EntityType]: No data fixer registered for entity mmorpg:spider_pet
←[m←[33m[16:28:32] [modloading-worker-3/WARN] [minecraft/EntityType]: No data fixer registered for entity mmorpg:spirit_wolf_pet
←[m←[32m[16:28:32] [Server thread/INFO] [ne.mi.fm.DeferredWorkQueue/LOADING]: Dispatching synchronous work after CONSTRUCT: 2 jobs
←[m←[32m[16:28:32] [Server thread/INFO] [ne.mi.fm.DeferredWorkQueue/LOADING]: Synchronous work queue completed in 00:00:00.013
←[m←[32m[16:28:33] [Server thread/INFO] [behgameon/]: All Items registered.
←[m←[32m[16:28:33] [Server thread/INFO] [STDOUT/]: [com.robertx22.mine_and_slash.mmorpg.registers.common.GearItemRegisters:registerItems:120]: Registering Gear Items!
←[m←[32m[16:28:33] [Server thread/INFO] [mo.az.az.AzureRPGItemsMod/]: All Items registered.
←[m←[32m[16:28:33] [Server thread/INFO] [Bookshelf/]: Registering 10 global loot modifier serializers.
←[m←[32m[16:28:33] [Server thread/INFO] [STDOUT/]: [com.robertx22.mine_and_slash.mmorpg.registers.common.WorldGenRegisters:register:28]: Registering Mine and Slash Map World Gen
←[m←[32m[16:28:33] [Server thread/INFO] [Bookshelf/]: Registering 2 recipe serializers.
←[m←[32m[16:28:33] [Server thread/INFO] [Bookshelf/]: Registering 5 ingredient serializers.
←[m←[33m[16:28:33] [Server thread/WARN] [ne.mi.co.ForgeConfigSpec/CORE]: Configuration file C:\Users\JeanShamayin\Desktop\MINE RPG\RPG NOVO\config\journeymap-common.toml is not correct. Correcting
←[m←[33m[16:28:33] [Server thread/WARN] [ne.mi.co.ForgeConfigSpec/CORE]: Incorrect key admins.serverAdmins was corrected from [mysticdrew, 12341234132] to [mysticdrew, 12341234132]
←[m←[32m[16:28:33] [Server thread/INFO] [journeymap/]: Loading JourneyMap Forge Configs
←[m←[32m[16:28:33] [modloading-worker-1/INFO] [Bookshelf/]: Registering 2 command argument types.
←[m←[32m[16:28:33] [modloading-worker-1/INFO] [Bookshelf/]: Registering 13 loot condition types.
←[m←[32m[16:28:33] [modloading-worker-2/INFO] [co.ma.ma.co.ut.LogUtils/]: maessentials Setup main
←[m←[32m[16:28:33] [modloading-worker-3/INFO] [STDOUT/]: [com.robertx22.mine_and_slash.mmorpg.MMORPG:commonSetupEvent:149]: mmorpg:FMLCommonSetupEvent
←[m←[32m[16:28:33] [modloading-worker-1/INFO] [incontrol/]: Reading spawn rules from spawn.json
←[m←[32m[16:28:33] [modloading-worker-1/INFO] [incontrol/]: Reading spawn rules from summonaid.json
←[m←[32m[16:28:33] [modloading-worker-1/INFO] [incontrol/]: Reading spawn rules from potentialspawn.json
←[m←[32m[16:28:33] [modloading-worker-1/INFO] [incontrol/]: Reading spawn rules from loot.json
←[m←[32m[16:28:33] [modloading-worker-1/INFO] [incontrol/]: Reading spawn rules from experience.json
←[m←[32m[16:28:33] [Forge Version Check/INFO] [ne.mi.fm.VersionChecker/]: [usefulbackpacks] Starting version check at https://api.u-team.info/update/usefulbackpacks.json
←[m←[32m[16:28:34] [Server thread/INFO] [ne.mi.fm.DeferredWorkQueue/LOADING]: Dispatching synchronous work after COMMON_SETUP: 2 jobs
←[m←[32m[16:28:34] [Server thread/INFO] [Cucumber Library/]: Loaded cucumber-tags.json in 1 ms
←[m←[32m[16:28:34] [Server thread/INFO] [journeymap/]: Initializing Packet Registry
←[m←[32m[16:28:34] [Server thread/INFO] [ne.mi.fm.DeferredWorkQueue/LOADING]: Synchronous work queue completed in 00:00:00.010
←[m←[32m[16:28:34] [Server thread/INFO] [minecraft/DedicatedServer]: Loading properties
←[m←[32m[16:28:34] [Server thread/INFO] [minecraft/DedicatedServer]: Default game type: SURVIVAL
←[m←[32m[16:28:34] [Server thread/INFO] [minecraft/DedicatedServer]: Generating keypair
←[m←[32m[16:28:34] [Server thread/INFO] [minecraft/DedicatedServer]: Starting Minecraft server on *:25565
←[m←[32m[16:28:34] [Server thread/INFO] [minecraft/NetworkSystem]: Using default channel type
←[m←[32m[16:28:34] [Forge Version Check/INFO] [ne.mi.fm.VersionChecker/]: [usefulbackpacks] Found status: UP_TO_DATE Current: 1.9.4.63 Target: null
←[m←[32m[16:28:34] [Forge Version Check/INFO] [ne.mi.fm.VersionChecker/]: [bookshelf] Starting version check at https://updates.blamejared.com/get?n=bookshelf&gv=1.15.2
←[m←[33m[16:28:34] [Server thread/WARN] [minecraft/DedicatedServer]: **** SERVER IS RUNNING IN OFFLINE/INSECURE MODE!
←[m←[33m[16:28:34] [Server thread/WARN] [minecraft/DedicatedServer]: The server will make no attempt to authenticate usernames. Beware.
←[m←[33m[16:28:34] [Server thread/WARN] [minecraft/DedicatedServer]: While this makes the game possible to play without internet access, it also opens up the ability for hackers to connect with any username they choose.
←[m←[33m[16:28:34] [Server thread/WARN] [minecraft/DedicatedServer]: To change this, set "online-mode" to "true" in the server.properties file.
←[m←[32m[16:28:34] [modloading-worker-3/INFO] [STDOUT/]: [com.robertx22.mine_and_slash.mmorpg.MMORPG:interModEnqueue:159]: mmorpg:InterModEnqueueEvent
←[m←[32m[16:28:34] [modloading-worker-0/INFO] [STDOUT/]: [com.robertx22.mine_and_slash.mmorpg.MMORPG:interModProcessEvent:165]: mmorpg:InterModProcessEvent
←[m←[33m[16:28:34] [Server thread/WARN] [ne.mi.co.ForgeConfigSpec/CORE]: Configuration file .\world\serverconfig\authmod-server.toml is not correct. Correcting
←[m←[33m[16:28:34] [Server thread/WARN] [ne.mi.co.ForgeConfigSpec/CORE]: Configuration file .\world\serverconfig\MineAndSlash-Server.toml is not correct. Correcting
←[m←[32m[16:28:35] [Server thread/INFO] [minecraft/DedicatedServer]: Preparing level "world"
←[m←[32m[16:28:35] [Forge Version Check/INFO] [ne.mi.fm.VersionChecker/]: [bookshelf] Found status: BETA_OUTDATED Current: 5.6.38 Target: 5.6.40
←[m←[32m[16:28:35] [Forge Version Check/INFO] [ne.mi.fm.VersionChecker/]: [uteamcore] Starting version check at https://api.u-team.info/update/uteamcore.json
←[m←[32m[16:28:35] [Forge Version Check/INFO] [ne.mi.fm.VersionChecker/]: [uteamcore] Found status: UP_TO_DATE Current: 2.11.0.156 Target: null
←[m←[32m[16:28:35] [Forge Version Check/INFO] [ne.mi.fm.VersionChecker/]: [maessentials] Starting version check at https://raw.githubusercontent.com/Maciej916/Ma-Essentials/1.15.2/update.json
←[m←[32m[16:28:35] [Server thread/INFO] [ne.mi.co.DimensionManager/DIMS]: Registered dimension mmorpg:resettable_dungeon of type mmorpg:resettable_dungeon and id 3
←[m←[32m[16:28:35] [Server thread/INFO] [ne.mi.co.DimensionManager/DIMS]: Registered dimension utilityworlds:mining_world_3 of type utilityworlds:mining_world and id 4
←[m←[32m[16:28:35] [Server thread/INFO] [ne.mi.co.DimensionManager/DIMS]: Registered dimension utilityworlds:void_world_4 of type utilityworlds:void_world and id 5
←[m←[32m[16:28:35] [Forge Version Check/INFO] [ne.mi.fm.VersionChecker/]: [maessentials] Found status: OUTDATED Current: 1.15.2-3.1.0 Target: 3.1.1
←[m←[32m[16:28:35] [Forge Version Check/INFO] [ne.mi.fm.VersionChecker/]: [forge] Starting version check at https://files.minecraftforge.net/maven/net/minecraftforge/forge/promotions_slim.json
←[m←[32m[16:28:35] [Server thread/INFO] [minecraft/SimpleReloadableResourceManager]: Reloading ResourceManager: useful_backpacks-1.15.2-1.9.4.63.jar, u_team_core-1.15.2-2.11.0.156.jar, authmod-4.0.jar, Cucumber-1.15.2-3.0.6.jar, behgameon-1.15.2-1.3.0.jar, WorldProtector+1.15.2.jar, ftb-ranks-1.0.0.3.jar, item-filters-2.2.0.14.jar, Mine+and+Slash-1.15.2-3.6.14.jar, jei-1.15.2-6.0.0.4.jar, AzureRPGItems+1.15.2-1.3.3.jar, incontrol-1.15-4.0.3.jar, curios-FORGE-1.15.2-2.0.2.2.jar, Waystones_1.15.2-6.0.1.jar, journeymap-1.15.2-5.7.0beta1.jar, ftb-gui-library-1.0.0.14.jar, ftb-quests-2.0.2.246.jar, GrandEconomy-1.15.2-1.5.4.jar, Bookshelf-1.15.2-5.6.38.jar, EnchantmentDescriptions-1.15.2-2.0.8.jar, AppleSkin-mc1.15.2-forge-1.0.13.jar, Morpheus-1.15.2-4.2.50.jar, Ma-Essentials-1.15.2-3.1.0.jar, confdespawnt_1.15-1.1.jar, JustEnoughResources-1.15.2-0.10.1.77.jar, UtilityWorlds-1.15.2_1.1.0.jar, forge-1.15.2-31.2.9-universal.jar, Default
←[m←[32m[16:28:36] [Forge Version Check/INFO] [ne.mi.fm.VersionChecker/]: [forge] Found status: OUTDATED Current: 31.2.9 Target: 31.2.20
←[m←[32m[16:28:36] [Server thread/INFO] [minecraft/RecipeManager]: Loaded 6 recipes
←[m←[32m[16:28:36] [Server thread/INFO] [minecraft/AdvancementList]: Loaded 890 advancements
←[m←[32m[16:28:36] [Server thread/INFO] [STDOUT/]: [com.robertx22.mine_and_slash.data_generation.BaseDataPackManager:apply:63]: TIER Registry succeeded loading: 6 datapack entries.
←[m←[32m[16:28:36] [Server thread/INFO] [STDOUT/]: [com.robertx22.mine_and_slash.data_generation.BaseDataPackManager:apply:63]: SET Registry succeeded loading: 30 datapack entries.
←[m←[32m[16:28:36] [Server thread/INFO] [STDOUT/]: [com.robertx22.mine_and_slash.data_generation.BaseDataPackManager:apply:63]: AFFIX Registry succeeded loading: 115 datapack entries.
←[m←[32m[16:28:36] [Server thread/INFO] [STDOUT/]: [com.robertx22.mine_and_slash.data_generation.BaseDataPackManager:apply:63]: RUNE Registry succeeded loading: 15 datapack entries.
←[m←[32m[16:28:36] [Server thread/INFO] [STDOUT/]: [com.robertx22.mine_and_slash.data_generation.BaseDataPackManager:apply:63]: MOB_AFFIX Registry succeeded loading: 13 datapack entries.
←[m←[32m[16:28:36] [Server thread/INFO] [STDOUT/]: [com.robertx22.mine_and_slash.data_generation.BaseDataPackManager:apply:63]: RUNEWORD Registry succeeded loading: 24 datapack entries.
←[m←[32m[16:28:36] [Server thread/INFO] [STDOUT/]: [com.robertx22.mine_and_slash.data_generation.BaseDataPackManager:apply:63]: UNIQUE_GEAR Registry succeeded loading: 90 datapack entries.
←[m←[32m[16:28:37] [Server thread/INFO] [STDOUT/]: [com.robertx22.mine_and_slash.data_generation.BaseDataPackManager:apply:63]: COMPATIBLE_ITEM Registry succeeded loading: 466 datapack entries.
←[m←[32m[16:28:37] [Server thread/INFO] [STDOUT/]: [com.robertx22.mine_and_slash.data_generation.rarities.BaseRarityDatapackManager:apply:42]: Starting to register rarity datapacks on the server from datapacks
←[m←[32m[16:28:37] [Server thread/INFO] [STDOUT/]: [com.robertx22.mine_and_slash.data_generation.rarities.BaseRarityDatapackManager:apply:62]: Rarity loading succeeded.
←[m←[32m[16:28:37] [Server thread/INFO] [minecraft/MinecraftServer]: Preparing start region for dimension minecraft:overworld
←[m←[32m[16:28:38] [Server thread/INFO] [minecraft/LoggingChunkStatusListener]: Preparing spawn area: 0%
←[m←[32m[16:28:38] [Server thread/INFO] [minecraft/LoggingChunkStatusListener]: Preparing spawn area: 0%
←[m←[32m[16:28:38] [Server thread/INFO] [minecraft/LoggingChunkStatusListener]: Preparing spawn area: 0%
←[m←[32m[16:28:39] [Server thread/INFO] [minecraft/LoggingChunkStatusListener]: Preparing spawn area: 81%
←[m←[32m[16:28:39] [Server thread/INFO] [minecraft/LoggingChunkStatusListener]: Time elapsed: 2081 ms
←[m←[32m[16:28:39] [Server thread/INFO] [minecraft/DedicatedServer]: Done (5.011s)! For help, type "help"
←[m←[32m[16:28:39] [Server thread/INFO] [AuthMod/]: Re-using existing authentication register.
←[m←[32m[16:28:39] [Server thread/INFO] [AuthMod/]: Use guard %s
←[m←[32m[16:28:39] [Server thread/INFO] [AuthMod/]: Registering /login command
←[m←[32m[16:28:39] [Server thread/INFO] [AuthMod/]: Registering /logged command
←[m←[32m[16:28:39] [Server thread/INFO] [AuthMod/]: Registering /register command
←[m←[32m[16:28:39] [Server thread/INFO] [AuthMod/]: Registering /changepassword command
←[m←[32m[16:28:39] [Server thread/INFO] [Bookshelf/]: Registering 1 commands.
←[m←[32m[16:28:39] [Server thread/INFO] [co.ma.ma.co.ut.LogUtils/]: maessentials Setup world
←[m←[32m[16:28:39] [Server thread/INFO] [co.ma.ma.co.ut.LogUtils/]: maessentials Mod is running on server
←[m←[32m[16:28:39] [Server thread/INFO] [co.ma.ma.co.ut.LogUtils/]: maessentials Loading data
←[m←[32m[16:28:39] [Server thread/INFO] [co.ma.ma.co.ut.LogUtils/]: maessentials Data loaded
←[m←[32m[16:28:40] [Server thread/INFO] [FTB Quests/]: Loading quests from C:\Users\JeanShamayin\Desktop\MINE RPG\RPG NOVO\config\ftbquests\quests
←[m←[32m[16:28:40] [Server thread/INFO] [FTB Quests/]: Loaded 1 chapters, 8 quests, 8 tasks and 21 rewards. In total, 39 objects
←[m←[32m[16:28:40] [Server thread/INFO] [FTB Ranks/]: Loading command nodes...
←[m←[32m[16:28:40] [Server thread/INFO] [FTB Ranks/]: Loaded 1456 command nodes
←[m←[32m[16:28:40] [Server thread/INFO] [FTB Ranks/]: Loaded 4 ranks
←[m←[32m[16:28:40] [Server thread/INFO] [STDOUT/]: [com.robertx22.mine_and_slash.mmorpg.registers.server.CommandRegister:Register:22]: Registering Mine and Slash Commands.
←[m←[32m[16:28:40] [Server thread/INFO] [STDOUT/]: [com.robertx22.mine_and_slash.registry.SlashRegistry:unregisterInvalidEntries:278]: Starting Mine and Slash Registry auto validation.
←[m←[32m[16:28:40] [Server thread/INFO] [STDOUT/]: [com.robertx22.mine_and_slash.registry.SlashRegistry:unregisterInvalidEntries:294]: All Mine and Slash registries appear valid.
←[m←[32m[16:28:40] [Server thread/INFO] [minecraft/ChunkManager]: ThreadedAnvilChunkStorage (void_world_4): All chunks are saved
←[m←[32m[16:28:40] [Server thread/INFO] [minecraft/ChunkManager]: ThreadedAnvilChunkStorage (DIM-1): All chunks are saved
←[m←[32m[16:28:40] [Server thread/INFO] [minecraft/ChunkManager]: ThreadedAnvilChunkStorage (DIM1): All chunks are saved
←[m←[32m[16:28:40] [Server thread/INFO] [minecraft/ChunkManager]: ThreadedAnvilChunkStorage (mining_world_3): All chunks are saved
←[m←[32m[16:28:40] [Server thread/INFO] [minecraft/ChunkManager]: ThreadedAnvilChunkStorage (resettable_dungeon): All chunks are saved`

**Comment by Chocorean** [comment]
I honestly don't think your issue is related to authmod

**Comment by JeanShamayin** [comment]
Yes, I can, it works normally, all players enter normally

**Comment by Chocorean** [comment]
Weird. Can you list the mods you are using please?
Also make sure to put the mod only in the server folder, not in the client
