### ISSUE TITLE
Only one player can register using DATABASE strategy without emails

### ISSUE THREAD

**Issue by alexdevteam** [Chocorean/authmod#35]
**Describe the bug**

When trying to register, a single message is sent, "Someone has already registered with this username or email", even though only one other user has registered (with a different username)

**To Reproduce**

1. Connect to the server, which has email requirement OFF
2. Register with one account
3. Try to register with another completely different one

**Expected behavior**

It should let me register.

**Versions**

Authmod 3.0, Minecraft 1.12.2

**Comment by Chocorean** [comment]
Working correctly with FILE strategy at least as of b015d8

**Comment by Chocorean** [comment]
Bug has been reproduced with database strategy. @Mcdostone can you check for 1.15.2 if this is working properly?

**Comment by Chocorean** [comment]
Issue identified:
Right now, using DATABASE strategy and without using emails, only one player can register because the email field is required and unique, but it is also equal to `''` for everyone.

**Comment by Chocorean** [comment]
@Mcdostone I think this is still happening on your branch

**Comment by Chocorean** [comment]
@Mcdostone I just modified the readme (removed the unique constraint on email) and changed the query in `src/main/java/io/chocorean/authmod/guard/datasource/db/playerDAO.java:public IPlayer find(IPlayer player) throws SQLException`
