### ISSUE TITLE
Plugin Not Working on 1.16.5

### ISSUE THREAD

**Issue by SheroxGG** [Chocorean/authmod#47]
We are creating a FTB Oceancraft server, and we will like to do it for everyone. So we were looking for a auth plugin, but this one doesnt seem to work. The server starts properly and everything, but it doesnt read the plugin, it does not create any config neither.

You can donwload OceanCraft from FTB app

**Versions**

Latest 1.16.5 1.0.0

**Log files**

[latest.log](https://github.com/Chocorean/authmod/files/7364472/latest.log)

**Comment by Chocorean** [comment]
I’d advise you to try version 1.0.1 to see if it changes anything, else you’ll have to wait for the next version of authmod
