### ISSUE TITLE
Cant execute commands and optional name entering

### ISSUE THREAD

**Issue by Oshi41** [Chocorean/authmod#9]
Hello!
In Handler.java there is no check for player entering in not-registering group, that means every command is blocking(
That condition is forgotten
**descriptors.containsKey(event.getSender())**
Method can be looks like:
` @SubscribeEvent(priority= EventPriority.HIGHEST)
    public static void onCommand(CommandEvent event){
        String name = event.getCommand().getCommandName();
        if (descriptors.containsKey(event.getSender()) && !(name.equals("register") || name.equals("login")) && (event.getSender() instanceof EntityPlayer) && event.isCancelable()) {
            event.setCanceled(true);
            ((EntityPlayerMP)event.getSender()).connection.sendPacket(new SPacketChat(new TextComponentString(AuthMod.getConfig().getMessage())));
        }
    }`

And you really need to make username as optional parameter in commands) In a commands you can check args length and if only one param is present, take name from IPlayer, casting it to EntityPlayer and get name from it.

Thank you)

BTW, it is possible to set no registered players gamemod to ADVENTURE (in Handler.java)
Seems like it can help

**Comment by Oshi41** [comment]
And I forgot: after executing Register comand, you just can create Login command and execute it)
You did it for user with idea to remember password? :)

**Comment by Mcdostone** [comment]
Hey Oshi41, thanks for your feedback, we really appreciate! We are still improving this project. Your remarks are right. The new release will be available soon :)

**Comment by Mcdostone** [comment]
I think this issue is fixed !
